# permissions for end users to view workers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-viewer-role
rules:
- apiGroups:
  - cloudasr.smartcommunitylab.it
  resources:
  - workers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudasr.smartcommunitylab.it
  resources:
  - workers/status
  verbs:
  - get
